package bm7

import (
	"encoding/hex"
	"encoding/json"
	"os"
	"testing"
)

type vector struct {
	Name     string `json:"name"`
	Type     uint8  `json:"type"`
	Flags    uint16 `json:"flags"`
	Session  uint64 `json:"session"`
	Epoch    uint64 `json:"epoch"`
	Sequence uint64 `json:"sequence"`
	Sender   string `json:"sender"`
	Lease    uint32 `json:"lease"`
	Priority uint32 `json:"priority"`
	Cost     uint32 `json:"cost"`
	State    uint8  `json:"state"`
	Packet   string `json:"packet"`
}

type vectorFile struct {
	Key     string   `json:"key"`
	Vectors []vector `json:"vectors"`
}

// TestPythonVectors decodes packets produced by the Python implementation,
// checks every field, and re-encodes them to prove byte-identical output.
// Set BM7_PY_VECTORS to the JSON file generated by tests/interop/gen_vectors.py.
func TestPythonVectors(t *testing.T) {
	path := os.Getenv("BM7_PY_VECTORS")
	if path == "" {
		t.Skip("BM7_PY_VECTORS not set")
	}
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	var vf vectorFile
	if err := json.Unmarshal(raw, &vf); err != nil {
		t.Fatal(err)
	}
	key := []byte(vf.Key)
	for _, v := range vf.Vectors {
		data, _ := hex.DecodeString(v.Packet)
		p, err := Decode(data, key)
		if err != nil {
			t.Fatalf("%s: decode: %v", v.Name, err)
		}
		sender, _ := hex.DecodeString(v.Sender)
		if p.Type != v.Type || p.Flags != v.Flags || p.Session != v.Session ||
			p.Epoch != v.Epoch || p.Sequence != v.Sequence || p.Lease != v.Lease ||
			string(p.Sender[:]) != string(sender) || p.Priority() != v.Priority ||
			p.Cost() != v.Cost || uint8(p.State()) != v.State {
			t.Fatalf("%s: field mismatch", v.Name)
		}
		p.Tag = [AuthLen]byte{}
		if hex.EncodeToString(Encode(p, key)) != v.Packet {
			t.Fatalf("%s: Go re-encode differs from Python bytes", v.Name)
		}
		if _, err := Decode(data, []byte("wrong-key")); err == nil {
			t.Fatalf("%s: wrong key accepted", v.Name)
		}
		if _, err := Decode(data[:len(data)-1], key); err == nil {
			t.Fatalf("%s: truncated packet accepted", v.Name)
		}
	}
}

// TestEmitGoVectors writes Go-encoded packets for Python to verify.
// Set BM7_GO_VECTORS to the output path.
func TestEmitGoVectors(t *testing.T) {
	path := os.Getenv("BM7_GO_VECTORS")
	if path == "" {
		t.Skip("BM7_GO_VECTORS not set")
	}
	key := []byte("bm7-interop-test-key")
	var out []vector
	for i, mt := range []uint8{MsgHello, MsgAdvertise, MsgClaim, MsgACK, MsgRelease, MsgError} {
		var p Packet
		p.Type, p.Flags, p.Session = mt, FlagActive, uint64(100+i)
		p.Epoch, p.Sequence, p.Lease = uint64(i+1), uint64(10*i+1), 5000
		copy(p.Sender[:], []byte("go-node-0123456"+string(rune('a'+i))))
		for j := 0; j < 16; j++ {
			p.Payload[j] = byte(0xA0 + j)
		}
		p.Payload[19], p.Payload[23], p.Payload[24] = byte(50+i), byte(i), byte(StateActive)
		out = append(out, vector{Name: "go", Type: mt, Flags: p.Flags, Session: p.Session,
			Epoch: p.Epoch, Sequence: p.Sequence, Sender: hex.EncodeToString(p.Sender[:]),
			Lease: p.Lease, Priority: uint32(50 + i), Cost: uint32(i), State: uint8(StateActive),
			Packet: hex.EncodeToString(Encode(p, key))})
	}
	b, _ := json.MarshalIndent(vectorFile{Key: string(key), Vectors: out}, "", " ")
	if err := os.WriteFile(path, b, 0o644); err != nil {
		t.Fatal(err)
	}
}

func TestUnknownFlagRejected(t *testing.T) {
	var p Packet
	p.Type, p.Flags = MsgHello, 0x8000
	if _, err := Decode(Encode(p, []byte("k")), []byte("k")); err == nil {
		t.Fatal("unknown flag accepted")
	}
}
